### ISSUE TITLE
Use Case Issue for HOL

### ISSUE THREAD

**Issue by brharr** [Microsoft/MCW-OSS-DevOps#1]
Although the Use Case for this particular workshop does make sense and it does teach the user a number of very good skills, but it is just replicating functionality that is already available in a more automated way within Web Apps under the Continuous Deployment tab. What would be better is if we were teaching something that is not available through an Azure feature, but that is also a more real world use case of "DevOps" using Jenkins. So a thought would be a set of tests that are performed against the code prior to actually doing a deployment or a set of "compilation" tasks such as linting or minification and then packaging the code before deployment. 

Even if we give them all the necessary testing scripts or processes to load into Jenkins, it will still help them understand how all of this comes together and then from a deployment perspective, deploying to something that does already integrate with Github, like a VM or a Custom Container in Web Apps would be a better real world demonstration and learning opportunity.

Thanks,
Brian

**Comment by DawnmarieDesJardins** [comment]
Labeling as an enhancement to be reviewed during the next update cycle.
