### ISSUE TITLE
Need to merge branches

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-OSS-DevOps#12]
Hi Michael,
This is the one where one editor looked at the HOLs and another looked at the WDS files.  Both created an edit branch.  I was going to merge those two together but there's a conflict because I think you said you'd updated files on the master at the same time.  You were going to take care of the conflict for me.
Dawnmarie

**Comment by mwasham** [comment]
already did.. just forgot to delete the branches. It's done now.
