### ISSUE TITLE
WDS - trainer guide

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-OSS-DevOps#18]
Lines 506 & 510 - Alt-text says "GitHub and Jenkins are depicted running in Azure..." The screenshot does not have Jenkins anywhere on it.

Please double check all the slide screenshots in the trainer's guide.  It looks like some of the slides were updated in the PPT deck but not in the trainer's guide.

**Comment by mwasham** [comment]
maybe you are referencing an old version? 

This is the description on 506 
A diagram that depicts a web based solution deployed in two regions with Azure Traffic Manager directing traffic to the closest one. In front of the web app is Azure CDN. The database is Azure Database for MySQL configured for geo-restore. GitHub and Jenkins are depicted running in Azure using virtual machines.

This is the pic 

![image](https://user-images.githubusercontent.com/1229364/45812973-f9640c80-bc96-11e8-84bb-16398d10b39f.png)


This is the description on 510 
A diagram that depicts a web based solution deployed in two regions with Azure Traffic Manager directing traffic to the closest one. In front of the web app is Azure CDN. The database is Azure Database for MySQL configured for geo-restore. Visual Studio Team Services is shown next to GitHub enterprise.

This is the pic

![image](https://user-images.githubusercontent.com/1229364/45813028-1b5d8f00-bc97-11e8-916d-01c1bc58c924.png)

**Comment by DawnmarieDesJardins** [comment]
Ah, thanks for checking!  I could have slipped back to the master branch without realizing.  Closing this issue.
