### ISSUE TITLE
MCW-OSS-DevOps/Hands-on lab/HOL step-by-step - OSS DevOp

### ISSUE THREAD

**Issue by SanjayWoorvakonda** [Microsoft/MCW-OSS-DevOps#20]
MCW-OSS-DevOps/Hands-on lab/HOL step-by-step - OSS DevOp -> 
Task 5: **Configure FTP deployment credentials Option** Page Missing in the Azure Portal.

MCW-OSS-DevOps/Hands-on lab/HOL step-by-step - OSS DevOp -> Before the HOL - OSS DevOps -> 
Task 2: Install the MySQL Workbench -> Download URL https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-6.3.10-winx64.msi. - is Broken , needs to be updated with latest URL below  "https://downloads.mysql.com/archives/workbench/"

**Comment by DawnmarieDesJardins** [comment]
Assigning to Michael for review during Nov updates

**Comment by fasalzaman** [comment]
The pull request yet to be approved will solve this issue.
