### ISSUE TITLE
GitHub Services are deprecated as of October 1, 2018

### ISSUE THREAD

**Issue by fasalzaman** [Microsoft/MCW-OSS-DevOps#21]
**In Exercise 3> Task 4 > Step 2 --- Add service option is not available.**

GitHub no longer supports GitHub Services as of October 1, 2018. Lab guide may need to update to use webhooks instead of GitHub services.

Reference : https://developer.github.com/changes/2018-04-25-github-services-deprecation/

**Comment by DawnmarieDesJardins** [comment]
Assigning to Michael for review during Nov update.

**Comment by fasalzaman** [comment]
The pull request yet to be approved will solve this issue.
Can you review and approve the PR raised by Shane Davis?
