### ISSUE TITLE
WDS trainer PPT, new slide after 34

### ISSUE THREAD

**Issue by gerwaldo** [Microsoft/MCW-OSS-DevOps#4]
Additional considerations
CI/CD workflow

Propose the solution that best fits customer needs & OSS preferences:
Cusotmer can use OSS tools on Azure IaaS (still needs administration, maintainance and customization)
Customer can use VSTS with Jenkins integration (leverage investment in Jenkins build but use VSTS relaease management, VSTS is a fully managed service)
Customer can switch to VSTS (best integration and open standards, git, Linux/macOS & Windows Build and Release, VSTS is a fully managed service)

OSS customers not familiar with Visual Studio & VSTS can use Azure DevOps projects to setup CI/CD from the Azure portal

Microsoft acquired GitHub which will remain a seperate service/product but expect additional integration to deploy & use Azure services

**Comment by DawnmarieDesJardins** [comment]
Labeling as an enhancement to be reviewed during the next update cycle.
